{{- include "ignition-common.ganCA" (dict "context" .) }}
---
{{- include "ignition-common.ganMetroKeystore" (dict "password" .Values.ignition.gan.keystorePassword "context" .) }}
---
{{- include "ignition-common.ganCertificate" (dict "commonName" "ignition" "dnsNames" (list (printf "*.%s" (include "ignition.name" .))) "context" .) }}
