{{ include "ignition-common.service" (dict "values" .Values.ignition "Release" .Release "Chart" .Chart "Values" .Values) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ignition.name" . }}-primary
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ignition.labels" . | nindent 4 }}
spec:
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "ignition.name" . }}-0
    {{- include "ignition.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.ignition.service.ports.http }}
    protocol: TCP
    targetPort: http
  - name: https
    port: {{ .Values.ignition.service.ports.https }}
    protocol: TCP
    targetPort: https
  - name: gan
    port: {{ .Values.ignition.service.ports.gan }}
    protocol: TCP
    targetPort: gan
  type: ClusterIP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ignition.name" . }}-backup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ignition.labels" . | nindent 4 }}
spec:
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "ignition.name" . }}-1
    {{- include "ignition.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.ignition.service.ports.http }}
    protocol: TCP
    targetPort: http
  - name: https
    port: {{ .Values.ignition.service.ports.https }}
    protocol: TCP
    targetPort: https
  - name: gan
    port: {{ .Values.ignition.service.ports.gan }}
    protocol: TCP
    targetPort: gan
  type: ClusterIP
  clusterIP: None