apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ignition.name" . }}
  labels:
    {{- include "ignition.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ include "ignition.name" . }}
      {{- include "ignition.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "ignition.name" . }}
  replicas: {{ if .Values.ignition.redundancy.enabled }}2{{ else }}1{{ end }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  template:
    metadata:
      labels:
        {{- include "ignition.selectorLabels" . | nindent 8 }}
        name: {{ include "ignition.name" . }}
    spec:
      serviceAccountName: {{ include "ignition.serviceAccountName" . }}
      terminationGracePeriodSeconds: 60
      securityContext:
        {{- toYaml .Values.ignition.securityContext | nindent 8 }}
      {{- if .Values.affinity.enabled }}
      affinity:
        podAntiAffinity:
          {{- if eq .Values.affinity.type "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: name
                  operator: In
                  values:
                  - {{ include "ignition.name" . }}
              topologyKey: {{ .Values.affinity.topologyKey }}
          {{- else }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - {{ include "ignition.name" . }}
            topologyKey: {{ .Values.affinity.topologyKey }}
          {{- end }}
      {{- end }}
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: gateway
        securityContext:
          {{- toYaml .Values.ignition.securityContext | nindent 10 }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {{ .Values.ignition.resources | toYaml | nindent 10 }}
        args: {{ .Values.ignition.args | toYaml | nindent 8 }}
        ports:
        - name: http
          containerPort: {{ .Values.ignition.service.ports.http }}
        - name: https
          containerPort: {{ .Values.ignition.service.ports.https }}
        - name: gan
          containerPort: {{ .Values.ignition.service.ports.gan }}
        envFrom:
        - configMapRef:
            name: {{ include "ignition.name" . }}-config
        - secretRef:
            name: {{ include "ignition.name" . }}-secrets
        env:
        - name: EAM_SETUP_INSTALLSELECTION
          value: {{ .Values.ignition.eam.role | quote }}
        - name: GATEWAY_SYSTEM_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

        volumeMounts:
{{ include "ignition-common.volumeMounts" (dict "name" (include "ignition.name" .) "values" .Values.ignition) | nindent 8 }}
        {{- if .Values.ignition.readinessProbe.enabled }}
        readinessProbe:
{{ include "ignition-common.probes" (dict "probe" .Values.ignition.readinessProbe) | nindent 10 }}
        {{- end }}
        {{- if .Values.ignition.livenessProbe.enabled }}
        livenessProbe:
{{ include "ignition-common.probes" (dict "probe" .Values.ignition.livenessProbe) | nindent 10 }}
        {{- end }}
      initContainers:
{{ include "ignition-common.initContainer.preconfigure" (dict "name" (include "ignition.name" .) "image" .Values.image "values" .Values.ignition "replicas" (ternary 2 1 .Values.ignition.redundancy.enabled)) | nindent 6 }}
      volumes:
{{ include "ignition-common.volumes" (dict "name" (include "ignition.name" .) "values" .Values.ignition "ganTlsSecretName" (printf "%s-gan-tls" (include "ignition.name" .)) "commonScriptsConfigMapName" (include "ignition-common.scriptsName" .)) | nindent 6 }}

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: {{- toYaml .Values.ignition.persistence.accessModes | nindent 8 }}
    {{- if .Values.ignition.persistence.storageClassName }}
    {{- if (eq "-" .Values.ignition.persistence.storageClassName) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.ignition.persistence.storageClassName }}"
    {{- end }}
    {{- end }}
      resources:
        requests:
          storage: {{ .Values.ignition.persistence.size }}