version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"

  # Maintain dependencies for Helm Charts
  - package-ecosystem: "helm"
    directory: "/charts/common"
    schedule:
      interval: "weekly"

  - package-ecosystem: "helm"
    directory: "/charts/failover"
    schedule:
      interval: "weekly"

  - package-ecosystem: "helm"
    directory: "/charts/scaleout"
    schedule:
      interval: "weekly"
