{{- if .Values.ignition.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.name" . }}-config
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data: {{ .Values.ignition.config | toYaml | nindent 2 }}
{{- end }}