{{- include "ignition-common.ganCA" (dict "context" .) }}
---
{{- include "ignition-common.ganMetroKeystore" (dict "password" .Values.frontend.gan.keystorePassword "context" .) }}
---
{{- include "ignition-common.ganCertificate" (dict "name" "frontend" "commonName" (printf "%s-frontend" (include "ignition.name" .)) "dnsNames" (list (printf "*.%s-frontend" (include "ignition.name" .))) "context" .) }}
---
{{- include "ignition-common.ganCertificate" (dict "name" "backend" "commonName" (printf "%s-backend" (include "ignition.name" .)) "dnsNames" (list (printf "*.%s-backend" (include "ignition.name" .))) "context" .) }}
