{{- range $component := list "frontend" "backend" }}
{{- $componentConfig := index $.Values $component }}
{{- if $componentConfig.secrets }}
---
{{ include "ignition-common.secret" (dict "name" $component "secrets" $componentConfig.secrets "sealedSecrets" ($componentConfig.sealedSecrets | default false) "context" $) }}
{{- end }}
{{- end }}