apiVersion: v2
name: ignition-failover
description: A Helm chart for failover Ignition Gateway with combined
  frontend/backend functionality
type: application
version: 1.1.0
appVersion: "8.1.47"
dependencies:
  - name: ignition-common
    version: 0.1.0
    repository: "file://../common"
