apiVersion: v2
name: ignition-failover
description: A Helm chart for failover Ignition Gateway with combined
  frontend/backend functionality
type: application
version: 1.2.0
dependencies:
  - name: ignition-common
    version: "*"
    repository: "file://../common"
