apiVersion: v2
name: ignition-scaleout
description: A Helm chart for failover Ignition Gateway with scalable frontend
  client functionality
type: application
version: 2.0.0
appVersion: "8.3.1"
dependencies:
  - name: ignition-common
    version: "*"
    repository: "file://../common"
