apiVersion: v2
name: ignition-scaleout
description: A Helm chart for failover Ignition Gateway with scalable frontend
  client functionality
type: application
version: 1.1.2
dependencies:
  - name: ignition-common
    version: 0.2.0
    repository: "file://../common"
