apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ignition.name" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ignition.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ignition.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "ignition.name" . }}-frontend
  replicas: {{ .Values.frontend.redundancy.replicas }}
  template:
    metadata:
      labels:
        {{- include "ignition.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ignition.serviceAccountName" . }}
      securityContext:
        fsGroup: {{ .Values.frontend.securityContext.fsGroup }}
        runAsGroup: {{ .Values.frontend.securityContext.runAsGroup }}
        runAsNonRoot: {{ .Values.frontend.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.frontend.securityContext.runAsUser }}
        seccompProfile:
          {{- toYaml .Values.frontend.securityContext.seccompProfile | nindent 10 }}
      {{- if .Values.affinity.enabled }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - {{ include "ignition.name" . }}
            topologyKey: kubernetes.io/hostname
      {{- end }}
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: gateway
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: {{ .Values.frontend.securityContext.readOnlyRootFilesystem }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {{ .Values.frontend.resources | toYaml | nindent 10 }}
        args: {{ .Values.frontend.args | toYaml | nindent 8 }}
        ports:
        - name: http
          containerPort: {{ .Values.frontend.service.ports.http }}
        - name: https
          containerPort: {{ .Values.frontend.service.ports.https }}
        - name: gan
          containerPort: {{ .Values.frontend.service.ports.gan }}
        envFrom:
        - configMapRef:
            name: {{ include "ignition.name" . }}-frontend-config
        - secretRef:
            name: {{ include "ignition.name" . }}-frontend-secrets
        env:
        {{- $backendReplicas := (ternary 2 1 .Values.backend.redundancy.enabled) }}
        {{- range $i, $e := until (int $backendReplicas) }}
        - name: GATEWAY_NETWORK_{{ $i }}_HOST
          value: {{ include "ignition-common.podFQDN" (dict "name" (printf "%s-backend" (include "ignition.name" $)) "ordinal" $i) | quote }}
        {{- end }}
        - name: EAM_SETUP_INSTALLSELECTION
          value: {{ .Values.frontend.eam.role | quote }}
        - name: EAM_AGENT_CONTROLLERSERVERNAME
          value: "backend"
        - name: GATEWAY_SYSTEM_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
{{ include "ignition-common.volumeMounts" (dict "name" (include "ignition.name" .) "values" .Values.frontend "machineIdSubPath" "frontend-machine-id") | nindent 8 }}
        {{- if .Values.frontend.readinessProbe.enabled }}
        readinessProbe:
{{ include "ignition-common.probes" (dict "probe" .Values.frontend.readinessProbe) | nindent 10 }}
        {{- end }}
        {{- if .Values.frontend.livenessProbe.enabled }}
        livenessProbe:
{{ include "ignition-common.probes" (dict "probe" .Values.frontend.livenessProbe) | nindent 10 }}
        {{- end }}
      initContainers:
{{ include "ignition-common.initContainer.preconfigure" (dict "name" (include "ignition.name" .) "secretName" (printf "%s-frontend-secrets" (include "ignition.name" .)) "image" .Values.image "values" .Values.frontend "replicas" 1 "context" .) | nindent 6 }}
      volumes:
      - name: data
        emptyDir: {}
{{ include "ignition-common.volumes" (dict "name" (include "ignition.name" .) "values" .Values.frontend "ganTlsSecretName" (printf "%s-frontend-gan-tls" (include "ignition.name" .)) "commonScriptsConfigMapName" (include "ignition-common.scriptsName" .)) | nindent 6 }}

