{{ include "ignition-common.service" (dict "name" "backend" "values" .Values.backend "Release" .Release "Chart" .Chart "Values" .Values) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ignition.name" . }}-backend-primary
  labels:
    {{- include "ignition.labels" . | nindent 4 }}
spec:
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "ignition.name" . }}-backend-0
    {{- include "ignition.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: 8088
    protocol: TCP
    targetPort: http
  - name: https
    port: 8043
    protocol: TCP
    targetPort: https
  - name: gan
    port: 8060
    protocol: TCP
    targetPort: gan
  type: ClusterIP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ignition.name" . }}-backend-backup
  labels:
    {{- include "ignition.labels" . | nindent 4 }}
spec:
  selector:
    statefulset.kubernetes.io/pod-name: {{ include "ignition.name" . }}-backend-1
    {{- include "ignition.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: 8088
    protocol: TCP
    targetPort: http
  - name: https
    port: 8043
    protocol: TCP
    targetPort: https
  - name: gan
    port: 8060
    protocol: TCP
    targetPort: gan
  type: ClusterIP
  clusterIP: None
