apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ignition.name" . }}-backend
  labels:
    {{- include "ignition.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      name: {{ include "ignition.name" . }}-backend
      {{- include "ignition.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "ignition.name" . }}-backend
  replicas: {{ if .Values.backend.redundancy.enabled }}2{{ else }}1{{ end }}
  updateStrategy:
    # type: OnDelete
    # rollingUpdate: null
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  template:
    metadata:
      labels:
        {{- include "ignition.selectorLabels" . | nindent 8 }}
        name: {{ include "ignition.name" . }}-backend
    spec:
      serviceAccountName: {{ include "ignition.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.backend.securityContext | nindent 8 }}
      {{- if .Values.affinity.enabled }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - {{ include "ignition.name" . }}-backend
            topologyKey: kubernetes.io/hostname
      {{- end }}
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: gateway
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {{ .Values.backend.resources | toYaml | nindent 10 }}
        args: {{ .Values.backend.args | toYaml | nindent 8 }}
        ports:
        - name: http
          containerPort: {{ .Values.backend.service.ports.http }}
        - name: https
          containerPort: {{ .Values.backend.service.ports.https }}
        - name: gan
          containerPort: {{ .Values.backend.service.ports.gan }}
        envFrom:
        - configMapRef:
            name: {{ include "ignition.name" . }}-backend-config
        - secretRef:
            name: {{ include "ignition.name" . }}-backend-secrets
        env:
        - name: EAM_SETUP_INSTALLSELECTION
          value: {{ .Values.backend.eam.role | quote }}

        volumeMounts:
{{ include "ignition-common.volumeMounts" (dict "name" (include "ignition.name" .) "values" .Values.backend "machineIdSubPath" "backend-machine-id") | nindent 8 }}
        {{- if .Values.backend.readinessProbe.enabled }}
        readinessProbe:
{{ include "ignition-common.probes" (dict "probe" .Values.backend.readinessProbe) | nindent 10 }}
        {{- end }}
        {{- if .Values.backend.livenessProbe.enabled }}
        livenessProbe:
{{ include "ignition-common.probes" (dict "probe" .Values.backend.livenessProbe) | nindent 10 }}
        {{- end }}
      initContainers:
{{ include "ignition-common.initContainer.preconfigure" (dict "name" (include "ignition.name" .) "image" .Values.image "values" .Values.backend "replicas" (ternary 2 1 .Values.backend.redundancy.enabled)) | nindent 6 }}
      volumes:
{{ include "ignition-common.volumes" (dict "name" (include "ignition.name" .) "values" .Values.backend "ganTlsSecretName" (printf "%s-backend-gan-tls" (include "ignition.name" .)) "commonScriptsConfigMapName" (include "ignition-common.scriptsName" .)) | nindent 6 }}

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: {{- toYaml .Values.backend.persistence.accessModes | nindent 8 }}
    {{- if .Values.backend.persistence.storageClassName }}
    {{- if (eq "-" .Values.backend.persistence.storageClassName) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.backend.persistence.storageClassName }}"
    {{- end }}
    {{- end }}
      resources:
        requests:
          storage: {{ .Values.backend.persistence.size }}
