name: Version

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  call-testing:
    uses: ./.github/workflows/testing.yaml

  version:
    needs: call-testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/release-please-action@v4
        with:
          config-file: .github/release.json
          manifest-file: .github/.release.json
