name: Version and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  testing:
    uses: ./.github/workflows/testing.yaml

  version:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          config-file: .github/release.json
          manifest-file: .github/.release.json

      - name: Configure Git
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        if: ${{ steps.release.outputs.releases_created }}
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Update dependencies
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          for dir in charts/*; do
            if [ -d "$dir" ]; then
              helm dependency build "$dir"
            fi
          done

      - name: Run chart-releaser
        if: ${{ steps.release.outputs.releases_created }}
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts
          pages_branch: main
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"